library(charlatan)
charlatan::ch_generate()

charlatan::ch_color_name(5)
charlatan::ch_company(5)
charlatan::ch_credit_card_number(5)
charlatan::ch_credit_card_provider(5)
charlatan::ch_credit_card_security_code(5)
charlatan::ch_currency(5)
charlatan::ch_date_time(5)
charlatan::ch_doi(5)
charlatan::ch_double(5)
charlatan::ch_element_element(5)
charlatan::ch_element_symbol(5)
charlatan::ch_gene_sequence(5)
charlatan::ch_hex_color(5)
charlatan::ch_integer(5)
charlatan::ch_job(5)
charlatan::ch_lat(5)
charlatan::ch_lnorm(5)
charlatan::ch_lon(5)
charlatan::ch_missing(5)
charlatan::ch_name(5)
charlatan::ch_norm(5)
charlatan::ch_phone_number(5)
charlatan::ch_position(5)
charlatan::ch_rgb_color(5)
charlatan::ch_rgb_css_color(5)
charlatan::ch_safe_color_name(5)
charlatan::ch_safe_hex_color(5)
charlatan::ch_taxonomic_epithet(5)
charlatan::ch_taxonomic_genus(5)
charlatan::ch_taxonomic_species(5)
charlatan::ch_timezone(5)
charlatan::ch_unif(5)
charlatan::ch_unix_time(5)

ap <- charlatan::AddressProvider$new()
ap$address()




